services:
  migrations:
    build:
      context: ./
      dockerfile: ./migrations/Dockerfile
    image: "ghcr.io/pixelating-community/web-migrations:latest"
    command: ["node", "migrate.mjs"]
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    restart: "no"
