services:
  postgres:
    image: "postgres:18-alpine3.22"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=64MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=32MB"
      - "-c"
      - "effective_cache_size=128MB"
      - "-c"
      - "max_connections=25"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        order: stop-first
      resources:
        limits:
          cpus: "0.3"
          memory: 280M
        reservations:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: "ghcr.io/pixelating-community/web:${WEB_SHA}"

    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
      - EL_KEY
      - NEXT_PUBLIC_URL
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - REFLECTION_ACCESS_SECRET
      - SSE_BROADCAST_KEY
    environment:
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=384"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.7"
          memory: 480M
        reservations:
          cpus: "0.2"
          memory: 256M

networks:
  app_network:
    driver: overlay
    attachable: true

secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_DB:
    external: true
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY:
    external: true
  EL_KEY:
    external: true
  NEXT_PUBLIC_URL:
    external: true
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    external: true
  STRIPE_SECRET_KEY:
    external: true
  STRIPE_WEBHOOK_SECRET:
    external: true
  REFLECTION_ACCESS_SECRET:
    external: true
  SSE_BROADCAST_KEY:
    external: true

volumes:
  postgres_data:
    driver: local
