services:
  postgres:
    image: "postgres:16-alpine3.20"
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      start_period: 30s

  app:
    image: "ghcr.io/pixelating-community/web:latest"
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: postgres

volumes:
  postgres_data:
