name: web-prod

services:
  postgres:
    image: postgres:18-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    image: ${WEB_IMAGE:-ghcr.io/pixelating-community/web:main}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REQUIRE_EXISTING_DATA: ${REQUIRE_EXISTING_DATA:-0}
    ports:
      - "3000:3000"
    command: ["sh", "-lc", "bun run migrate && bun run start"]

volumes:
  postgres_data:
    name: web_postgres_data
