/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSplatRouteImport } from './routes/t.$'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiPRouteImport } from './routes/api/p'
import { Route as ApiObjRouteImport } from './routes/api/obj'
import { Route as TTopicUlRouteImport } from './routes/t.$topic.ul'
import { Route as TTopicToolsRouteImport } from './routes/t.$topic.tools'
import { Route as PIdCommitRouteImport } from './routes/p.$id.commit'
import { Route as ApiTTokenRouteImport } from './routes/api/t/token'
import { Route as ApiTARouteImport } from './routes/api/t/a'
import { Route as ApiTTopicRouteImport } from './routes/api/t/$topic'
import { Route as ApiRIdRouteImport } from './routes/api/r/$id'
import { Route as ApiPIdRouteImport } from './routes/api/p/$id'
import { Route as ApiObjYtRouteImport } from './routes/api/obj/yt'
import { Route as ApiObjUploadRouteImport } from './routes/api/obj/upload'
import { Route as ApiObjMergeStatusRouteImport } from './routes/api/obj/merge-status'
import { Route as ApiPIdReflectionsRouteImport } from './routes/api/p/$id/reflections'
import { Route as ApiPIdPromptRouteImport } from './routes/api/p/$id/prompt'
import { Route as ApiPIdCRouteImport } from './routes/api/p/$id/c'
import { Route as ApiPIdAudioSnippetsRouteImport } from './routes/api/p/$id/audio-snippets'
import { Route as ApiPIdAudioMixRouteImport } from './routes/api/p/$id/audio-mix'
import { Route as ApiPIdAlignRouteImport } from './routes/api/p/$id/align'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSplatRoute = TSplatRouteImport.update({
  id: '/t/$',
  path: '/t/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPRoute = ApiPRouteImport.update({
  id: '/api/p',
  path: '/api/p',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjRoute = ApiObjRouteImport.update({
  id: '/api/obj',
  path: '/api/obj',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicUlRoute = TTopicUlRouteImport.update({
  id: '/t/$topic/ul',
  path: '/t/$topic/ul',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicToolsRoute = TTopicToolsRouteImport.update({
  id: '/t/$topic/tools',
  path: '/t/$topic/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdCommitRoute = PIdCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => PIdRoute,
} as any)
const ApiTTokenRoute = ApiTTokenRouteImport.update({
  id: '/api/t/token',
  path: '/api/t/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTARoute = ApiTARouteImport.update({
  id: '/api/t/a',
  path: '/api/t/a',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTTopicRoute = ApiTTopicRouteImport.update({
  id: '/api/t/$topic',
  path: '/api/t/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRIdRoute = ApiRIdRouteImport.update({
  id: '/api/r/$id',
  path: '/api/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPIdRoute = ApiPIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPRoute,
} as any)
const ApiObjYtRoute = ApiObjYtRouteImport.update({
  id: '/yt',
  path: '/yt',
  getParentRoute: () => ApiObjRoute,
} as any)
const ApiObjUploadRoute = ApiObjUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiObjRoute,
} as any)
const ApiObjMergeStatusRoute = ApiObjMergeStatusRouteImport.update({
  id: '/merge-status',
  path: '/merge-status',
  getParentRoute: () => ApiObjRoute,
} as any)
const ApiPIdReflectionsRoute = ApiPIdReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdPromptRoute = ApiPIdPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdCRoute = ApiPIdCRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdAudioSnippetsRoute = ApiPIdAudioSnippetsRouteImport.update({
  id: '/audio-snippets',
  path: '/audio-snippets',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdAudioMixRoute = ApiPIdAudioMixRouteImport.update({
  id: '/audio-mix',
  path: '/audio-mix',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdAlignRoute = ApiPIdAlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => ApiPIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/obj/merge-status': typeof ApiObjMergeStatusRoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/obj/yt': typeof ApiObjYtRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/audio-mix': typeof ApiPIdAudioMixRoute
  '/api/p/$id/audio-snippets': typeof ApiPIdAudioSnippetsRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/obj/merge-status': typeof ApiObjMergeStatusRoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/obj/yt': typeof ApiObjYtRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/audio-mix': typeof ApiPIdAudioMixRoute
  '/api/p/$id/audio-snippets': typeof ApiPIdAudioSnippetsRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/obj/merge-status': typeof ApiObjMergeStatusRoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/obj/yt': typeof ApiObjYtRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/audio-mix': typeof ApiPIdAudioMixRoute
  '/api/p/$id/audio-snippets': typeof ApiPIdAudioSnippetsRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/obj/merge-status'
    | '/api/obj/upload'
    | '/api/obj/yt'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/commit'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/audio-mix'
    | '/api/p/$id/audio-snippets'
    | '/api/p/$id/c'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/obj/merge-status'
    | '/api/obj/upload'
    | '/api/obj/yt'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/commit'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/audio-mix'
    | '/api/p/$id/audio-snippets'
    | '/api/p/$id/c'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
  id:
    | '__root__'
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/obj/merge-status'
    | '/api/obj/upload'
    | '/api/obj/yt'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/commit'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/audio-mix'
    | '/api/p/$id/audio-snippets'
    | '/api/p/$id/c'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiObjRoute: typeof ApiObjRouteWithChildren
  ApiPRoute: typeof ApiPRouteWithChildren
  PIdRoute: typeof PIdRouteWithChildren
  TSplatRoute: typeof TSplatRoute
  ApiRIdRoute: typeof ApiRIdRoute
  ApiTTopicRoute: typeof ApiTTopicRoute
  ApiTARoute: typeof ApiTARoute
  ApiTTokenRoute: typeof ApiTTokenRoute
  TTopicToolsRoute: typeof TTopicToolsRoute
  TTopicUlRoute: typeof TTopicUlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$': {
      id: '/t/$'
      path: '/t/$'
      fullPath: '/t/$'
      preLoaderRoute: typeof TSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p': {
      id: '/api/p'
      path: '/api/p'
      fullPath: '/api/p'
      preLoaderRoute: typeof ApiPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/obj': {
      id: '/api/obj'
      path: '/api/obj'
      fullPath: '/api/obj'
      preLoaderRoute: typeof ApiObjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/ul': {
      id: '/t/$topic/ul'
      path: '/t/$topic/ul'
      fullPath: '/t/$topic/ul'
      preLoaderRoute: typeof TTopicUlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/tools': {
      id: '/t/$topic/tools'
      path: '/t/$topic/tools'
      fullPath: '/t/$topic/tools'
      preLoaderRoute: typeof TTopicToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/commit': {
      id: '/p/$id/commit'
      path: '/commit'
      fullPath: '/p/$id/commit'
      preLoaderRoute: typeof PIdCommitRouteImport
      parentRoute: typeof PIdRoute
    }
    '/api/t/token': {
      id: '/api/t/token'
      path: '/api/t/token'
      fullPath: '/api/t/token'
      preLoaderRoute: typeof ApiTTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t/a': {
      id: '/api/t/a'
      path: '/api/t/a'
      fullPath: '/api/t/a'
      preLoaderRoute: typeof ApiTARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t/$topic': {
      id: '/api/t/$topic'
      path: '/api/t/$topic'
      fullPath: '/api/t/$topic'
      preLoaderRoute: typeof ApiTTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r/$id': {
      id: '/api/r/$id'
      path: '/api/r/$id'
      fullPath: '/api/r/$id'
      preLoaderRoute: typeof ApiRIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/$id': {
      id: '/api/p/$id'
      path: '/$id'
      fullPath: '/api/p/$id'
      preLoaderRoute: typeof ApiPIdRouteImport
      parentRoute: typeof ApiPRoute
    }
    '/api/obj/yt': {
      id: '/api/obj/yt'
      path: '/yt'
      fullPath: '/api/obj/yt'
      preLoaderRoute: typeof ApiObjYtRouteImport
      parentRoute: typeof ApiObjRoute
    }
    '/api/obj/upload': {
      id: '/api/obj/upload'
      path: '/upload'
      fullPath: '/api/obj/upload'
      preLoaderRoute: typeof ApiObjUploadRouteImport
      parentRoute: typeof ApiObjRoute
    }
    '/api/obj/merge-status': {
      id: '/api/obj/merge-status'
      path: '/merge-status'
      fullPath: '/api/obj/merge-status'
      preLoaderRoute: typeof ApiObjMergeStatusRouteImport
      parentRoute: typeof ApiObjRoute
    }
    '/api/p/$id/reflections': {
      id: '/api/p/$id/reflections'
      path: '/reflections'
      fullPath: '/api/p/$id/reflections'
      preLoaderRoute: typeof ApiPIdReflectionsRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/prompt': {
      id: '/api/p/$id/prompt'
      path: '/prompt'
      fullPath: '/api/p/$id/prompt'
      preLoaderRoute: typeof ApiPIdPromptRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/c': {
      id: '/api/p/$id/c'
      path: '/c'
      fullPath: '/api/p/$id/c'
      preLoaderRoute: typeof ApiPIdCRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/audio-snippets': {
      id: '/api/p/$id/audio-snippets'
      path: '/audio-snippets'
      fullPath: '/api/p/$id/audio-snippets'
      preLoaderRoute: typeof ApiPIdAudioSnippetsRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/audio-mix': {
      id: '/api/p/$id/audio-mix'
      path: '/audio-mix'
      fullPath: '/api/p/$id/audio-mix'
      preLoaderRoute: typeof ApiPIdAudioMixRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/align': {
      id: '/api/p/$id/align'
      path: '/align'
      fullPath: '/api/p/$id/align'
      preLoaderRoute: typeof ApiPIdAlignRouteImport
      parentRoute: typeof ApiPIdRoute
    }
  }
}

interface ApiObjRouteChildren {
  ApiObjMergeStatusRoute: typeof ApiObjMergeStatusRoute
  ApiObjUploadRoute: typeof ApiObjUploadRoute
  ApiObjYtRoute: typeof ApiObjYtRoute
}

const ApiObjRouteChildren: ApiObjRouteChildren = {
  ApiObjMergeStatusRoute: ApiObjMergeStatusRoute,
  ApiObjUploadRoute: ApiObjUploadRoute,
  ApiObjYtRoute: ApiObjYtRoute,
}

const ApiObjRouteWithChildren =
  ApiObjRoute._addFileChildren(ApiObjRouteChildren)

interface ApiPIdRouteChildren {
  ApiPIdAlignRoute: typeof ApiPIdAlignRoute
  ApiPIdAudioMixRoute: typeof ApiPIdAudioMixRoute
  ApiPIdAudioSnippetsRoute: typeof ApiPIdAudioSnippetsRoute
  ApiPIdCRoute: typeof ApiPIdCRoute
  ApiPIdPromptRoute: typeof ApiPIdPromptRoute
  ApiPIdReflectionsRoute: typeof ApiPIdReflectionsRoute
}

const ApiPIdRouteChildren: ApiPIdRouteChildren = {
  ApiPIdAlignRoute: ApiPIdAlignRoute,
  ApiPIdAudioMixRoute: ApiPIdAudioMixRoute,
  ApiPIdAudioSnippetsRoute: ApiPIdAudioSnippetsRoute,
  ApiPIdCRoute: ApiPIdCRoute,
  ApiPIdPromptRoute: ApiPIdPromptRoute,
  ApiPIdReflectionsRoute: ApiPIdReflectionsRoute,
}

const ApiPIdRouteWithChildren =
  ApiPIdRoute._addFileChildren(ApiPIdRouteChildren)

interface ApiPRouteChildren {
  ApiPIdRoute: typeof ApiPIdRouteWithChildren
}

const ApiPRouteChildren: ApiPRouteChildren = {
  ApiPIdRoute: ApiPIdRouteWithChildren,
}

const ApiPRouteWithChildren = ApiPRoute._addFileChildren(ApiPRouteChildren)

interface PIdRouteChildren {
  PIdCommitRoute: typeof PIdCommitRoute
}

const PIdRouteChildren: PIdRouteChildren = {
  PIdCommitRoute: PIdCommitRoute,
}

const PIdRouteWithChildren = PIdRoute._addFileChildren(PIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiObjRoute: ApiObjRouteWithChildren,
  ApiPRoute: ApiPRouteWithChildren,
  PIdRoute: PIdRouteWithChildren,
  TSplatRoute: TSplatRoute,
  ApiRIdRoute: ApiRIdRoute,
  ApiTTopicRoute: ApiTTopicRoute,
  ApiTARoute: ApiTARoute,
  ApiTTokenRoute: ApiTTokenRoute,
  TTopicToolsRoute: TTopicToolsRoute,
  TTopicUlRoute: TTopicUlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
