/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSplatRouteImport } from './routes/t.$'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiPRouteImport } from './routes/api/p'
import { Route as ApiObjRouteImport } from './routes/api/obj'
import { Route as TTopicUlRouteImport } from './routes/t.$topic.ul'
import { Route as TTopicToolsRouteImport } from './routes/t.$topic.tools'
import { Route as PIdSwRouteImport } from './routes/p.$id.sw'
import { Route as PIdSRouteImport } from './routes/p.$id.s'
import { Route as PIdCommitRouteImport } from './routes/p.$id.commit'
import { Route as PIdCancelRouteImport } from './routes/p.$id.cancel'
import { Route as ApiTTokenRouteImport } from './routes/api/t/token'
import { Route as ApiTARouteImport } from './routes/api/t/a'
import { Route as ApiTTopicRouteImport } from './routes/api/t/$topic'
import { Route as ApiSHRouteImport } from './routes/api/s/h'
import { Route as ApiRIdRouteImport } from './routes/api/r/$id'
import { Route as ApiPIdRouteImport } from './routes/api/p/$id'
import { Route as ApiObjUploadRouteImport } from './routes/api/obj/upload'
import { Route as ApiCARouteImport } from './routes/api/c/a'
import { Route as ApiCIdRouteImport } from './routes/api/c/$id'
import { Route as ApiPIdWriteAccessRouteImport } from './routes/api/p/$id/write-access'
import { Route as ApiPIdVerifySessionRouteImport } from './routes/api/p/$id/verify-session'
import { Route as ApiPIdVerifyRouteImport } from './routes/api/p/$id/verify'
import { Route as ApiPIdReflectionsRouteImport } from './routes/api/p/$id/reflections'
import { Route as ApiPIdPromptRouteImport } from './routes/api/p/$id/prompt'
import { Route as ApiPIdCollectRouteImport } from './routes/api/p/$id/collect'
import { Route as ApiPIdCRouteImport } from './routes/api/p/$id/c'
import { Route as ApiPIdAlignRouteImport } from './routes/api/p/$id/align'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSplatRoute = TSplatRouteImport.update({
  id: '/t/$',
  path: '/t/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPRoute = ApiPRouteImport.update({
  id: '/api/p',
  path: '/api/p',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjRoute = ApiObjRouteImport.update({
  id: '/api/obj',
  path: '/api/obj',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicUlRoute = TTopicUlRouteImport.update({
  id: '/t/$topic/ul',
  path: '/t/$topic/ul',
  getParentRoute: () => rootRouteImport,
} as any)
const TTopicToolsRoute = TTopicToolsRouteImport.update({
  id: '/t/$topic/tools',
  path: '/t/$topic/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdSwRoute = PIdSwRouteImport.update({
  id: '/sw',
  path: '/sw',
  getParentRoute: () => PIdRoute,
} as any)
const PIdSRoute = PIdSRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => PIdRoute,
} as any)
const PIdCommitRoute = PIdCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => PIdRoute,
} as any)
const PIdCancelRoute = PIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => PIdRoute,
} as any)
const ApiTTokenRoute = ApiTTokenRouteImport.update({
  id: '/api/t/token',
  path: '/api/t/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTARoute = ApiTARouteImport.update({
  id: '/api/t/a',
  path: '/api/t/a',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTTopicRoute = ApiTTopicRouteImport.update({
  id: '/api/t/$topic',
  path: '/api/t/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSHRoute = ApiSHRouteImport.update({
  id: '/api/s/h',
  path: '/api/s/h',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRIdRoute = ApiRIdRouteImport.update({
  id: '/api/r/$id',
  path: '/api/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPIdRoute = ApiPIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPRoute,
} as any)
const ApiObjUploadRoute = ApiObjUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiObjRoute,
} as any)
const ApiCARoute = ApiCARouteImport.update({
  id: '/api/c/a',
  path: '/api/c/a',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCIdRoute = ApiCIdRouteImport.update({
  id: '/api/c/$id',
  path: '/api/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPIdWriteAccessRoute = ApiPIdWriteAccessRouteImport.update({
  id: '/write-access',
  path: '/write-access',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdVerifySessionRoute = ApiPIdVerifySessionRouteImport.update({
  id: '/verify-session',
  path: '/verify-session',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdVerifyRoute = ApiPIdVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdReflectionsRoute = ApiPIdReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdPromptRoute = ApiPIdPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdCollectRoute = ApiPIdCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdCRoute = ApiPIdCRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => ApiPIdRoute,
} as any)
const ApiPIdAlignRoute = ApiPIdAlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => ApiPIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/c/$id': typeof ApiCIdRoute
  '/api/c/a': typeof ApiCARoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/s/h': typeof ApiSHRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/cancel': typeof PIdCancelRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/p/$id/s': typeof PIdSRoute
  '/p/$id/sw': typeof PIdSwRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/collect': typeof ApiPIdCollectRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
  '/api/p/$id/verify': typeof ApiPIdVerifyRoute
  '/api/p/$id/verify-session': typeof ApiPIdVerifySessionRoute
  '/api/p/$id/write-access': typeof ApiPIdWriteAccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/c/$id': typeof ApiCIdRoute
  '/api/c/a': typeof ApiCARoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/s/h': typeof ApiSHRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/cancel': typeof PIdCancelRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/p/$id/s': typeof PIdSRoute
  '/p/$id/sw': typeof PIdSwRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/collect': typeof ApiPIdCollectRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
  '/api/p/$id/verify': typeof ApiPIdVerifyRoute
  '/api/p/$id/verify-session': typeof ApiPIdVerifySessionRoute
  '/api/p/$id/write-access': typeof ApiPIdWriteAccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/obj': typeof ApiObjRouteWithChildren
  '/api/p': typeof ApiPRouteWithChildren
  '/p/$id': typeof PIdRouteWithChildren
  '/t/$': typeof TSplatRoute
  '/api/c/$id': typeof ApiCIdRoute
  '/api/c/a': typeof ApiCARoute
  '/api/obj/upload': typeof ApiObjUploadRoute
  '/api/p/$id': typeof ApiPIdRouteWithChildren
  '/api/r/$id': typeof ApiRIdRoute
  '/api/s/h': typeof ApiSHRoute
  '/api/t/$topic': typeof ApiTTopicRoute
  '/api/t/a': typeof ApiTARoute
  '/api/t/token': typeof ApiTTokenRoute
  '/p/$id/cancel': typeof PIdCancelRoute
  '/p/$id/commit': typeof PIdCommitRoute
  '/p/$id/s': typeof PIdSRoute
  '/p/$id/sw': typeof PIdSwRoute
  '/t/$topic/tools': typeof TTopicToolsRoute
  '/t/$topic/ul': typeof TTopicUlRoute
  '/api/p/$id/align': typeof ApiPIdAlignRoute
  '/api/p/$id/c': typeof ApiPIdCRoute
  '/api/p/$id/collect': typeof ApiPIdCollectRoute
  '/api/p/$id/prompt': typeof ApiPIdPromptRoute
  '/api/p/$id/reflections': typeof ApiPIdReflectionsRoute
  '/api/p/$id/verify': typeof ApiPIdVerifyRoute
  '/api/p/$id/verify-session': typeof ApiPIdVerifySessionRoute
  '/api/p/$id/write-access': typeof ApiPIdWriteAccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/c/$id'
    | '/api/c/a'
    | '/api/obj/upload'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/s/h'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/cancel'
    | '/p/$id/commit'
    | '/p/$id/s'
    | '/p/$id/sw'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/c'
    | '/api/p/$id/collect'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
    | '/api/p/$id/verify'
    | '/api/p/$id/verify-session'
    | '/api/p/$id/write-access'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/c/$id'
    | '/api/c/a'
    | '/api/obj/upload'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/s/h'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/cancel'
    | '/p/$id/commit'
    | '/p/$id/s'
    | '/p/$id/sw'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/c'
    | '/api/p/$id/collect'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
    | '/api/p/$id/verify'
    | '/api/p/$id/verify-session'
    | '/api/p/$id/write-access'
  id:
    | '__root__'
    | '/'
    | '/api/obj'
    | '/api/p'
    | '/p/$id'
    | '/t/$'
    | '/api/c/$id'
    | '/api/c/a'
    | '/api/obj/upload'
    | '/api/p/$id'
    | '/api/r/$id'
    | '/api/s/h'
    | '/api/t/$topic'
    | '/api/t/a'
    | '/api/t/token'
    | '/p/$id/cancel'
    | '/p/$id/commit'
    | '/p/$id/s'
    | '/p/$id/sw'
    | '/t/$topic/tools'
    | '/t/$topic/ul'
    | '/api/p/$id/align'
    | '/api/p/$id/c'
    | '/api/p/$id/collect'
    | '/api/p/$id/prompt'
    | '/api/p/$id/reflections'
    | '/api/p/$id/verify'
    | '/api/p/$id/verify-session'
    | '/api/p/$id/write-access'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiObjRoute: typeof ApiObjRouteWithChildren
  ApiPRoute: typeof ApiPRouteWithChildren
  PIdRoute: typeof PIdRouteWithChildren
  TSplatRoute: typeof TSplatRoute
  ApiCIdRoute: typeof ApiCIdRoute
  ApiCARoute: typeof ApiCARoute
  ApiRIdRoute: typeof ApiRIdRoute
  ApiSHRoute: typeof ApiSHRoute
  ApiTTopicRoute: typeof ApiTTopicRoute
  ApiTARoute: typeof ApiTARoute
  ApiTTokenRoute: typeof ApiTTokenRoute
  TTopicToolsRoute: typeof TTopicToolsRoute
  TTopicUlRoute: typeof TTopicUlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$': {
      id: '/t/$'
      path: '/t/$'
      fullPath: '/t/$'
      preLoaderRoute: typeof TSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p': {
      id: '/api/p'
      path: '/api/p'
      fullPath: '/api/p'
      preLoaderRoute: typeof ApiPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/obj': {
      id: '/api/obj'
      path: '/api/obj'
      fullPath: '/api/obj'
      preLoaderRoute: typeof ApiObjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/ul': {
      id: '/t/$topic/ul'
      path: '/t/$topic/ul'
      fullPath: '/t/$topic/ul'
      preLoaderRoute: typeof TTopicUlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$topic/tools': {
      id: '/t/$topic/tools'
      path: '/t/$topic/tools'
      fullPath: '/t/$topic/tools'
      preLoaderRoute: typeof TTopicToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id/sw': {
      id: '/p/$id/sw'
      path: '/sw'
      fullPath: '/p/$id/sw'
      preLoaderRoute: typeof PIdSwRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/s': {
      id: '/p/$id/s'
      path: '/s'
      fullPath: '/p/$id/s'
      preLoaderRoute: typeof PIdSRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/commit': {
      id: '/p/$id/commit'
      path: '/commit'
      fullPath: '/p/$id/commit'
      preLoaderRoute: typeof PIdCommitRouteImport
      parentRoute: typeof PIdRoute
    }
    '/p/$id/cancel': {
      id: '/p/$id/cancel'
      path: '/cancel'
      fullPath: '/p/$id/cancel'
      preLoaderRoute: typeof PIdCancelRouteImport
      parentRoute: typeof PIdRoute
    }
    '/api/t/token': {
      id: '/api/t/token'
      path: '/api/t/token'
      fullPath: '/api/t/token'
      preLoaderRoute: typeof ApiTTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t/a': {
      id: '/api/t/a'
      path: '/api/t/a'
      fullPath: '/api/t/a'
      preLoaderRoute: typeof ApiTARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t/$topic': {
      id: '/api/t/$topic'
      path: '/api/t/$topic'
      fullPath: '/api/t/$topic'
      preLoaderRoute: typeof ApiTTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s/h': {
      id: '/api/s/h'
      path: '/api/s/h'
      fullPath: '/api/s/h'
      preLoaderRoute: typeof ApiSHRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r/$id': {
      id: '/api/r/$id'
      path: '/api/r/$id'
      fullPath: '/api/r/$id'
      preLoaderRoute: typeof ApiRIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/$id': {
      id: '/api/p/$id'
      path: '/$id'
      fullPath: '/api/p/$id'
      preLoaderRoute: typeof ApiPIdRouteImport
      parentRoute: typeof ApiPRoute
    }
    '/api/obj/upload': {
      id: '/api/obj/upload'
      path: '/upload'
      fullPath: '/api/obj/upload'
      preLoaderRoute: typeof ApiObjUploadRouteImport
      parentRoute: typeof ApiObjRoute
    }
    '/api/c/a': {
      id: '/api/c/a'
      path: '/api/c/a'
      fullPath: '/api/c/a'
      preLoaderRoute: typeof ApiCARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/c/$id': {
      id: '/api/c/$id'
      path: '/api/c/$id'
      fullPath: '/api/c/$id'
      preLoaderRoute: typeof ApiCIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/$id/write-access': {
      id: '/api/p/$id/write-access'
      path: '/write-access'
      fullPath: '/api/p/$id/write-access'
      preLoaderRoute: typeof ApiPIdWriteAccessRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/verify-session': {
      id: '/api/p/$id/verify-session'
      path: '/verify-session'
      fullPath: '/api/p/$id/verify-session'
      preLoaderRoute: typeof ApiPIdVerifySessionRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/verify': {
      id: '/api/p/$id/verify'
      path: '/verify'
      fullPath: '/api/p/$id/verify'
      preLoaderRoute: typeof ApiPIdVerifyRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/reflections': {
      id: '/api/p/$id/reflections'
      path: '/reflections'
      fullPath: '/api/p/$id/reflections'
      preLoaderRoute: typeof ApiPIdReflectionsRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/prompt': {
      id: '/api/p/$id/prompt'
      path: '/prompt'
      fullPath: '/api/p/$id/prompt'
      preLoaderRoute: typeof ApiPIdPromptRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/collect': {
      id: '/api/p/$id/collect'
      path: '/collect'
      fullPath: '/api/p/$id/collect'
      preLoaderRoute: typeof ApiPIdCollectRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/c': {
      id: '/api/p/$id/c'
      path: '/c'
      fullPath: '/api/p/$id/c'
      preLoaderRoute: typeof ApiPIdCRouteImport
      parentRoute: typeof ApiPIdRoute
    }
    '/api/p/$id/align': {
      id: '/api/p/$id/align'
      path: '/align'
      fullPath: '/api/p/$id/align'
      preLoaderRoute: typeof ApiPIdAlignRouteImport
      parentRoute: typeof ApiPIdRoute
    }
  }
}

interface ApiObjRouteChildren {
  ApiObjUploadRoute: typeof ApiObjUploadRoute
}

const ApiObjRouteChildren: ApiObjRouteChildren = {
  ApiObjUploadRoute: ApiObjUploadRoute,
}

const ApiObjRouteWithChildren =
  ApiObjRoute._addFileChildren(ApiObjRouteChildren)

interface ApiPIdRouteChildren {
  ApiPIdAlignRoute: typeof ApiPIdAlignRoute
  ApiPIdCRoute: typeof ApiPIdCRoute
  ApiPIdCollectRoute: typeof ApiPIdCollectRoute
  ApiPIdPromptRoute: typeof ApiPIdPromptRoute
  ApiPIdReflectionsRoute: typeof ApiPIdReflectionsRoute
  ApiPIdVerifyRoute: typeof ApiPIdVerifyRoute
  ApiPIdVerifySessionRoute: typeof ApiPIdVerifySessionRoute
  ApiPIdWriteAccessRoute: typeof ApiPIdWriteAccessRoute
}

const ApiPIdRouteChildren: ApiPIdRouteChildren = {
  ApiPIdAlignRoute: ApiPIdAlignRoute,
  ApiPIdCRoute: ApiPIdCRoute,
  ApiPIdCollectRoute: ApiPIdCollectRoute,
  ApiPIdPromptRoute: ApiPIdPromptRoute,
  ApiPIdReflectionsRoute: ApiPIdReflectionsRoute,
  ApiPIdVerifyRoute: ApiPIdVerifyRoute,
  ApiPIdVerifySessionRoute: ApiPIdVerifySessionRoute,
  ApiPIdWriteAccessRoute: ApiPIdWriteAccessRoute,
}

const ApiPIdRouteWithChildren =
  ApiPIdRoute._addFileChildren(ApiPIdRouteChildren)

interface ApiPRouteChildren {
  ApiPIdRoute: typeof ApiPIdRouteWithChildren
}

const ApiPRouteChildren: ApiPRouteChildren = {
  ApiPIdRoute: ApiPIdRouteWithChildren,
}

const ApiPRouteWithChildren = ApiPRoute._addFileChildren(ApiPRouteChildren)

interface PIdRouteChildren {
  PIdCancelRoute: typeof PIdCancelRoute
  PIdCommitRoute: typeof PIdCommitRoute
  PIdSRoute: typeof PIdSRoute
  PIdSwRoute: typeof PIdSwRoute
}

const PIdRouteChildren: PIdRouteChildren = {
  PIdCancelRoute: PIdCancelRoute,
  PIdCommitRoute: PIdCommitRoute,
  PIdSRoute: PIdSRoute,
  PIdSwRoute: PIdSwRoute,
}

const PIdRouteWithChildren = PIdRoute._addFileChildren(PIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiObjRoute: ApiObjRouteWithChildren,
  ApiPRoute: ApiPRouteWithChildren,
  PIdRoute: PIdRouteWithChildren,
  TSplatRoute: TSplatRoute,
  ApiCIdRoute: ApiCIdRoute,
  ApiCARoute: ApiCARoute,
  ApiRIdRoute: ApiRIdRoute,
  ApiSHRoute: ApiSHRoute,
  ApiTTopicRoute: ApiTTopicRoute,
  ApiTARoute: ApiTARoute,
  ApiTTokenRoute: ApiTTokenRoute,
  TTopicToolsRoute: TTopicToolsRoute,
  TTopicUlRoute: TTopicUlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
